version: "3.9"
services:
  dify-whatsapp:
    # image: warching/dify-whatsapp
    build: .
    ports:
      - "8000:80"
    command:
      - /bin/bash
      - -c
      - |
          uvicorn main:app --reload --host 0.0.0.0 --port 80
    env_file:
      - .env
    volumes:
      - ./main.py:/app/main.py
      - ./.env:/app/.env
    networks:
      - dify-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  dify-network: